# GLOBAL VARIABLES
export BASHDIR=$HOME/.config/bash

PATH="$HOME/.local/bin:$PATH"
PATH="$PATH:/home/fffai/.spicetify"
export PATH

export XDG_CONFIG_HOME="$HOME"/.config
export XDG_CACHE_HOME="$HOME"/.cache
export XDG_DATA_HOME="$HOME"/.local/share
export XDG_STATE_HOME="$HOME"/.local/state

# HOME CLEANUP
# ____________
export XINITRC="$XDG_CONFIG_HOME"/X11/xinitrc
export XSERVERRC="$XDG_CONFIG_HOME"/X11/xserverrc
export XAUTHORITY="$XDG_RUNTIME_DIR"/Xauthority
export XCURSOR_PATH=/usr/share/icons:"$XDG_DATA_HOME"/icons

export HISTFILE="${XDG_STATE_HOME}"/bash/history
export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc

export WINEPREFIX="$XDG_DATA_HOME"/wine

export TERMINFO="$XDG_DATA_HOME"/terminfo
export TERMINFO_DIRS="$XDG_DATA_HOME"/terminfo:/usr/share/terminfo
export LESSHISTFILE="$XDG_STATE_HOME"/less/history

export RUSTUP_HOME="$XDG_DATA_HOME"/rustup
export CARGO_HOME="$XDG_DATA_HOME"/cargo
export PYTHONSTARTUP=/etc/python/pythonrc
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java
export GRADLE_USER_HOME="$XDG_DATA_HOME"/gradle

export GOPATH="$XDG_DATA_HOME"/go
export CUDA_CACHE_PATH="$XDG_CACHE_HOME"/nv
export NUGET_PACKAGES="$XDG_CACHE_HOME"/NuGetPackages
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME"/npm/npmrc
export GNUPGHOME="$XDG_DATA_HOME"/gnupg
export JUPYTER_CONFIG_DIR="$XDG_CONFIG_HOME"/jupyter
export IPYTHONDIR="$XDG_CONFIG_HOME/ipython"

alias wget=wget --hsts-file="$XDG_DATA_HOME/wget-hsts"
alias nvidia-settings=nvidia-settings --config="$XDG_CONFIG_HOME"/nvidia/settings
alias lmms="lmms -c $XDG_CONFIG_HOME/lmms/lmmsrc.xml"
alias startx="startx $XINITRC"

# DEFAULT APPLICATIONS
# ____________________
export EDITOR=nvim
#export BROWSER=firefox
export TERM=kitty

# my aliases
alias sudo=doas
alias sudoedit="doas nvim"
alias vim=nvim
alias clr=clear

alias ls='ls --color=auto'
PS1="\W > "

#source ~/.local/share/nvim/mason/packages/jedi-language-server/venv/bin/activate
